import subprocess
import os
import platform
import datetime
import math
import uuid
import hashlib
import sys
import logging
import re
import json
import functools

is_win = sys.platform == "win32"
is_py_3 = sys.version_info[0] == 3
if is_win:
    if is_py_3:
        import winreg
    else:
        import _winreg as winreg
        import exceptions


#---------------------------------------------------------------------------------------------------
# Version class util
class Version:
    component_re = re.compile(r'(\d+ | \.)', re.VERBOSE)

    def __init__(self, s = None):
        if s:
            self.parse(s)

    def parse(self, s):
        components = [x for x in filter(lambda x: x and x != '.', self.component_re.split(s))]

        for i in range(len(components)):
            components[i] = int(components[i])

        self.components = components

    def __str__(self):
        return '.'.join([str(x) for x in self.components])

    def __eq__(self, other):
        return Version.cmp(self, other) == 0
    def __lt__(self, other):
        return Version.cmp(self, other) < 0
    def __gt__(self, other):
        return Version.cmp(self, other) > 0
    def __le__(self, other):
        return Version.cmp(self, other) <= 0
    def __ge__(self, other):
        return Version.cmp(self, other) >= 0

    @staticmethod
    def cmp(lhs, rhs):
        i = 0
        while True:
            if i == len(lhs.components):
                if i == len(rhs.components):
                    return 0
                else:
                    return -1
            else:
                if i == len(rhs.components):
                    return 1
                elif lhs.components[i] != rhs.components[i]:
                    return lhs.components[i] - rhs.components[i]
            i = i + 1

#---------------------------------------------------------------------------------------------------
# Internal commands

def _bootstrap_execute_command(args):
    try:
        return subprocess.check_output(args).decode('utf-8').splitlines()
    except:
        return None

def _bootstrap_emit_header(file):
    file.write('//--------------------------------------------------------------------------------------------------\n')
    file.write("// This file was generated by 'bootstrap.py'\n\n")
    
    
#---------------------------------------------------------------------------------------------------
# MSVS Locator service

if 'ProgramFiles(x86)' in os.environ:
    MSVC_DEFAULT_PATH = os.path.join(os.environ['ProgramFiles(x86)'], 'Microsoft Visual Studio', 'Installer', 'vswhere.exe')
else:
    MSVC_DEFAULT_PATH = None

def _msvc_find_vswhere():
    if MSVC_DEFAULT_PATH and os.path.exists(MSVC_DEFAULT_PATH):
        return MSVC_DEFAULT_PATH

    return None

def _msvc_get_installation(vswhere):
    args = [
        vswhere,
        '-utf8',
        '-latest',
        '-products', '*',
        '-format', 'json'
    ]
    
    result = subprocess.check_output(args).decode('utf-8')
    return json.loads(result)

def _locate_windows_sdk_kits():
    roots_key = r"SOFTWARE\Microsoft\Windows Kits\Installed Roots"
    roots = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, roots_key, 0, winreg.KEY_READ)

    pattern = re.compile(r'KitsRoot(\d+)')

    for i in range(0, winreg.QueryInfoKey(roots)[1]):
        (name, value, kind) = winreg.EnumValue(roots, i)
        
        if (name.startswith('KitsRoot') and kind == winreg.REG_SZ):
            windows_sdk_location = value

            match = pattern.match(name)

            if match:
                windows_sdk_version = match.group(1)
                break

    windows_sdk_kits = []

    for i in range(0, winreg.QueryInfoKey(roots)[0]):
        version : str = winreg.EnumKey(roots, i)
        windows_sdk_kits.append(Version(version))

    return (windows_sdk_location, windows_sdk_version, windows_sdk_kits)

def _find_highest_version(versions):
    return max(versions)

#---------------------------------------------------------------------------------------------------
# Generate BFF file with MSVC compiler

def generate_msvc_compiler_info():
    vswhere = _msvc_find_vswhere()
    vsinstance = _msvc_get_installation(vswhere)[0]
    vsname = vsinstance['displayName']
    vspath = vsinstance['installationPath']
    
    msvs_tools_version_location = os.path.join(vspath, 'VC', 'Auxiliary', 'Build', 'Microsoft.VCToolsVersion.default.txt')
    with open(msvs_tools_version_location, 'r') as file:
        vstools = file.read().splitlines()[0]

    #
    # Get Windows Kits locations
    #

    (windows_sdk_location, windows_sdk_version, windows_sdk_kits) = _locate_windows_sdk_kits()

    # Generate header
    with open('scripts/compiler.msvs.bff', 'w') as f:
        _bootstrap_emit_header(f)

        f.write(".VsToolsLocation = '{}'\n".format(vspath))
        f.write(".VsToolsName = '{}'\n".format(vsname))
        f.write(".VsToolsVersion = '{}'\n".format(vstools))
        f.write(".WindowsSdkLocation = '{}'\n".format(os.path.normpath(windows_sdk_location)))
        f.write(".WindowsKitVersion = '{}'\n".format(windows_sdk_version))
        f.write(".WindowsSdkVersion = '{}'\n".format(max(windows_sdk_kits)))


def generate_version_file():
    os.makedirs('./engine/include/Graphyte', exist_ok=True)
    with open('engine/include/Graphyte/Build.Version.hxx', 'w+') as file:
        os_version = platform.win32_ver()[1]
        os_host = platform.system()

        build_commit = _bootstrap_execute_command('git log -1 --format=%H')
        build_commit_short = _bootstrap_execute_command('git log -1 --format=%h')
        build_branch = _bootstrap_execute_command('git rev-parse --abbrev-ref HEAD')

        date = datetime.datetime.now()

        build_version_major = date.year - 2000
        build_version_minor = date.month
        build_version_release = date.timetuple().tm_yday
        build_version_build = math.floor((date - datetime.datetime(year = 2000, day = 1, month = 1)).total_seconds() / (60 * 15))
        build_timestamp = date.strftime("!%Y-%m-%dT%H:%M:%SZ")
        build_uuid = hashlib.sha256(b'graphyte').hexdigest()[0:32]

        file.write('#define GRAPHYTE_BUILD_OS_VERSION        "{}"\n'.format(os_version))
        file.write('#define GRAPHYTE_BUILD_OS_HOST           "{}"\n'.format(os_host))
        file.write('#define GRAPHYTE_BUILD_COMMIT            "{}"\n'.format(build_commit[0] or "<unknown>"))
        file.write('#define GRAPHYTE_BUILD_COMMIT_SHORT      "{}"\n'.format(build_commit_short[0] or "<unknown>"))
        file.write('#define GRAPHYTE_BUILD_BRANCH            "{}"\n'.format(build_branch[0] or "<unknown>"))
        file.write('#define GRAPHYTE_BUILD_UUID              "{}"\n'.format(build_uuid))
        file.write('#define GRAPHYTE_BUILD_VERSION           "{}.{}.{}.{}"\n'.format(
            build_version_major,
            build_version_minor,
            build_version_release,
            build_version_build
        ))

        file.write('#define GRAPHYTE_BUILD_VERSION_MAJOR     {}\n'.format(build_version_major))
        file.write('#define GRAPHYTE_BUILD_VERSION_MINOR     {}\n'.format(build_version_minor))
        file.write('#define GRAPHYTE_BUILD_VERSION_RELEASE   {}\n'.format(build_version_release))
        file.write('#define GRAPHYTE_BUILD_VERSION_BUILD     {}\n'.format(build_version_build))
        file.write('#define GRAPHYTE_BUILD_TIMESTAMP         "{}"\n'.format(build_timestamp))

if __name__ == "__main__":
    generate_version_file()

    if is_win:
        generate_msvc_compiler_info()
