-- OpenGL Loader generated by GLAD project.
--
-- OpenGL spec version: 4.6 core
--
-- > glad --profile core --generator c --spec gl --out-path .
-- > glad --profile core --generator c --spec wgl --out-path .
-- > glad --profile core --generator c --spec egl --out-path .
-- > glad --profile core --generator c --spec glx --out-path .

project "glad"
    language "C"
    kind "StaticLib"

    files {
        "include/**.h",

        "source/glad.c",
        "**.lua"
    }

    inlining "explicit"

    includedirs {
        "./include",
    }

    filter { "system:linux" }
        files {
            "source/glad_glx.c",
        }

    filter { "system:android" }
        files {
            "source/glad_egl.c",
        }
    filter { "system:windows" }
        files {
            "source/glad_wgl.c",
        }

    filter { "toolset:msc*" }
        ufinclude "false"
